name: nest-odoo-integration
region: lon

services:
  - name: api
    environment_slug: node-js
    github:
      repo: octosoft-ai/nest-odoo-integration
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: yarn install --frozen-lockfile && yarn prisma:generate && yarn build
    run_command: npx prisma migrate deploy && yarn start:prod
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xs

    health_check:
      http_path: /api/v1
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production

      - key: PORT
        scope: RUN_TIME
        value: "3000"

      - key: APP_HOSTNAME
        scope: RUN_TIME
        value: "0.0.0.0"

      - key: REDIS_URL
        scope: RUN_TIME
        value: redis://redis:6379

  - name: redis
    image:
      registry: library
      registry_type: DOCKER_HUB
      repository: redis
      tag: 7-alpine
    instance_count: 1
    instance_size_slug: basic-xxs
    internal_ports:
      - 6379

